/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Misc.Notes;


import Dao.notes;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JDesktopPane;

/**
 *
 * @author bansal
 */
public class Notes extends javax.swing.JInternalFrame{
  
Color foreground_color=Color.RED,background_volor=Color.WHITE;
JDesktopPane pane=null;
    /**
     * Creates new form SaleFatSnf
     */
    public Notes(JDesktopPane d){    
       
     
        initComponents();
    pane=d;
    pane.add(this);
try{    ArrayList<notes> nots=notes.get();

    Color c=new Color(nots.get(0).getRed(),nots.get(0).getGreen(),nots.get(0).getBlue());

    note0.setForeground(c);
    note0.setText(nots.get(0).getData());
    
    c=new Color(nots.get(1).getRed(),nots.get(1).getGreen(),nots.get(1).getBlue());
    note1.setForeground(c);
    note1.setText(nots.get(1).getData());
    
    c=new Color(nots.get(2).getRed(),nots.get(2).getGreen(),nots.get(2).getBlue());
    note2.setForeground(c);
    note2.setText(nots.get(2).getData());
    
    c=new Color(nots.get(3).getRed(),nots.get(3).getGreen(),nots.get(3).getBlue());
    note3.setForeground(c);
    note3.setText(nots.get(3).getData());
}catch(Exception e){e.printStackTrace();
    
}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note0 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        note1 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        note2 = new javax.swing.JEditorPane();
        save = new javax.swing.JButton();
        forground_color = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        note3 = new javax.swing.JEditorPane();
        forground_color1 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        forground_color2 = new javax.swing.JButton();
        save2 = new javax.swing.JButton();
        forground_color3 = new javax.swing.JButton();
        save3 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 228, 196));
        jPanel1.setForeground(new java.awt.Color(255, 228, 192));

        note0.setBackground(Constant_Notes_color.background_color);
        note0.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        note0.setForeground(Constant_Notes_color.foreground_color);
        jScrollPane1.setViewportView(note0);

        note1.setBackground(Constant_Notes_color.background_color);
        note1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        note1.setForeground(Constant_Notes_color.foreground_color);
        jScrollPane2.setViewportView(note1);

        note2.setBackground(Constant_Notes_color.background_color);
        note2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        note2.setForeground(Constant_Notes_color.foreground_color);
        jScrollPane3.setViewportView(note2);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        forground_color.setText("Change Forground Color");
        forground_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forground_colorActionPerformed(evt);
            }
        });

        note3.setBackground(Constant_Notes_color.background_color);
        note3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        note3.setForeground(Constant_Notes_color.foreground_color);
        jScrollPane4.setViewportView(note3);

        forground_color1.setText("Change Forground Color");
        forground_color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forground_color1ActionPerformed(evt);
            }
        });

        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        forground_color2.setText("Change Forground Color");
        forground_color2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forground_color2ActionPerformed(evt);
            }
        });

        save2.setText("Save");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });

        forground_color3.setText("Change Forground Color");
        forground_color3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forground_color3ActionPerformed(evt);
            }
        });

        save3.setText("Save");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(save2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forground_color2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(save3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forground_color3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forground_color, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save1)
                .addGap(18, 18, 18)
                .addComponent(forground_color1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(forground_color))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save2)
                            .addComponent(forground_color2)
                            .addComponent(save3)
                            .addComponent(forground_color3))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save1)
                            .addComponent(forground_color1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forground_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forground_colorActionPerformed

         NotesColorChooser c1=new NotesColorChooser(pane,"0");
        c1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_forground_colorActionPerformed

    private void forground_color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forground_color1ActionPerformed
      
        NotesColorChooser c1=new NotesColorChooser(pane,"1");
        c1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_forground_color1ActionPerformed

    private void forground_color2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forground_color2ActionPerformed

        NotesColorChooser c1=new NotesColorChooser(pane,"2");
        c1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_forground_color2ActionPerformed

    private void forground_color3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forground_color3ActionPerformed

        NotesColorChooser c1=new NotesColorChooser(pane,"3");
        c1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_forground_color3ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
try{
       notes note=new notes();
       note.setId(1);
       note.setRed((Notes.note0.getForeground()).getRed());
       note.setGreen((Notes.note0.getForeground()).getGreen());
       note.setBlue((Notes.note0.getForeground()).getBlue());
       note.setData(Notes.note0.getText());
       note.add();
}catch(Exception e){e.printStackTrace();
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
try{
     notes note=new notes();
       note.setId(2);
       note.setRed((Notes.note1.getForeground()).getRed());
       note.setGreen((Notes.note1.getForeground()).getGreen());
       note.setBlue((Notes.note1.getForeground()).getBlue());
       note.setData(Notes.note1.getText());
       note.add();        
}catch(Exception e){e.printStackTrace();
    
}// TODO add your handling code here:
    }//GEN-LAST:event_save1ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed

 try{       
     notes note=new notes();
       note.setId(3);
       note.setRed((Notes.note2.getForeground()).getRed());
       note.setGreen((Notes.note2.getForeground()).getGreen());
       note.setBlue((Notes.note2.getForeground()).getBlue());
       note.setData(Notes.note2.getText());
       note.add();
}catch(Exception e){e.printStackTrace();
    
}// TODO add your handling code here:
    }//GEN-LAST:event_save2ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed

 try{       
    notes note=new notes();
       note.setId(4);
       note.setRed((Notes.note3.getForeground()).getRed());
       note.setGreen((Notes.note3.getForeground()).getGreen());
       note.setBlue((Notes.note3.getForeground()).getBlue());
       note.setData(Notes.note3.getText());
       note.add();
}catch(Exception e){e.printStackTrace();
    
}// TODO add your handling code here:
    }//GEN-LAST:event_save3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forground_color;
    private javax.swing.JButton forground_color1;
    private javax.swing.JButton forground_color2;
    private javax.swing.JButton forground_color3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JEditorPane note0;
    public static javax.swing.JEditorPane note1;
    public static javax.swing.JEditorPane note2;
    public static javax.swing.JEditorPane note3;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    // End of variables declaration//GEN-END:variables

  
}
